<?php
echo $_SERVER['PHP_SELF'];
echo "<br> ['SERVER_NAME'] :";
echo $_SERVER['SERVER_NAME'];
echo "<br> ['HTTP_HOST'] :";
echo $_SERVER['HTTP_HOST'];
echo "<br> ['HTTP_REFERER'] :";
echo $_SERVER['HTTP_REFERER'];
echo "<br> ['HTTP_USER_AGENT'] :";
echo $_SERVER['HTTP_USER_AGENT'];
echo "<br> ['SCRIPT_NAME'] :";
echo $_SERVER['SCRIPT_NAME'];
echo "<br>['GATEWAY_INTERFACE'] : ";
echo $_SERVER['GATEWAY_INTERFACE'];
echo "<br>['SERVER_ADDR'] :  ";
echo $_SERVER['SERVER_ADDR'];
echo "<br>['SERVER_SOFTWARE'] :  ";
echo $_SERVER['SERVER_SOFTWARE'];
echo "<br>['SERVER_PROTOCOL'] :  ";
echo $_SERVER['SERVER_PROTOCOL'];
echo "<br>['REQUEST_METHOD'] :  ";
echo $_SERVER['REQUEST_METHOD'];
echo "<br>['REQUEST_TIME'] :  ";
echo $_SERVER['REQUEST_TIME'];
echo "<br>['QUERY_STRING'] :  ";
echo $_SERVER['QUERY_STRING'];
echo "<br>['HTTP_ACCEPT'] :  ";
echo $_SERVER['HTTP_ACCEPT'];
echo "<br>['HTTP_ACCEPT_CHARSET'] :  ";
echo $_SERVER['HTTP_ACCEPT_CHARSET'];
echo "<br>['HTTP_HOST'] :  ";
echo $_SERVER['HTTP_HOST'];
echo "<br>['HTTP_REFERER'] :  ";
echo $_SERVER['HTTP_REFERER'];
echo "<br>['HTTPS'] :  ";
echo $_SERVER['HTTPS'];
echo "<br>['REMOTE_ADDR'] :  ";
echo $_SERVER['REMOTE_ADDR'];
echo "<br>['REMOTE_HOST'] :  ";
echo $_SERVER['REMOTE_HOST'];
echo "<br>['REMOTE_PORT'] :  ";
echo $_SERVER['REMOTE_PORT'];
echo "<br>['SCRIPT_FILENAME'] :  ";
echo $_SERVER['SCRIPT_FILENAME'];
echo "<br>['SERVER_ADMIN'] :  ";
echo $_SERVER['SERVER_ADMIN'];
echo "<br>['SERVER_PORT'] :  ";
echo $_SERVER['SERVER_PORT'];
echo "<br>['SERVER_SIGNATURE'] :  ";
echo $_SERVER['SERVER_SIGNATURE'];
echo "<br>['PATH_TRANSLATED'] :  ";
echo $_SERVER['PATH_TRANSLATED'];
echo "<br>['SCRIPT_NAME'] :  ";
echo $_SERVER['SCRIPT_NAME'];
echo "<br>['SCRIPT_URI'] :  ";
echo $_SERVER['SCRIPT_URI'];
echo "<br>  :  ";